### ISSUE TITLE
Simulated_example.R "getParameterOrder" not available for .Call()

### ISSUE THREAD

**Issue by GodinA** [James-Thorson/spatial_factor_analysis#1]
Hi Jim, just started playing with your package and ran the Simulated_example.R but I get an error when I try to run the `MakeADFun` object function:

> Error in .Call("getParameterOrder", data, parameters, new.env(), PACKAGE = DLL) : "getParameterOrder" not available for .Call() for package "spatial_factor_analysis_v24"

Is there another TMB file that I need to compile/load first e.g., [called_from_R.cpp](https://github.com/kaskr/adcomp/blob/master/tmb_syntax/called_from_R.cpp)?

**Comment by James-Thorson** [comment]
Aurelie,

Thanks for your interested in the package, and sorry for the inconvenience in running the example.

Unfortunately, I just ran the example file from the two windows machines to which I have easy access, and neither had a problem.  

A few ideas:
1.  Have you confirmed that TMB is running correctly on your machine by running any of the examples distributed with the package?
2.  Have you tried any other machines to replicate the error?  In particular I don't have access to an apple machine in case that's what you're running.

Ultimately it'd be nice to have some process for automatically testing packages across operating systems, Rtool versions, R package version etc.  Of course I was hoping devtools took care of that.

cheers,
jim

**Comment by GodinA** [comment]
Ok thanks Jim,

Will look into this (yes I’m running it on OS X).
I’ll keep you posted!

Aurelie
On Jun 3, 2015, at 2:25 PM, Jim Thorson <notifications@github.com<mailto:notifications@github.com>> wrote:

Aurelie,

Thanks for your interested in the package, and sorry for the inconvenience in running the example.

Unfortunately, I just ran the example file from the two windows machines to which I have easy access, and neither had a problem.

A few ideas:
1. Have you confirmed that TMB is running correctly on your machine by running any of the examples distributed with the package?
2. Have you tried any other machines to replicate the error? In particular I don't have access to an apple machine in case that's what you're running.

Ultimately it'd be nice to have some process for automatically testing packages across operating systems, Rtool versions, R package version etc. Of course I was hoping devtools took care of that.

cheers,
jim

—
Reply to this email directly or view it on GitHubhttps://github.com/James-Thorson/spatial_factor_analysis/issues/1#issuecomment-108534033.

## 

Aurelie Cosandey-Godin, PhD
Dalhousie University, Department of Biology
godina@dal.camailto:godina@dal.ca | m: +1 902 499-0984

**Comment by GodinA** [comment]
Works just fine! My little glitch was associated with `TmbFile = paste0(system.file("executables", package="SpatialFA"),"/")` - which was the wrong working directory...

**Comment by James-Thorson** [comment]
Is that because macs store the CPP file in a different location?  It would
be good to figure out how to make the code work off-the-shelf for macs as
well as PCs.

jim

**Comment by GodinA** [comment]
Not sure... the path did bring me to `'.../Library/R/3.1/library/SpatialFA/executables/` with a `dir()` including all `.cpp`, `.o`, `.dll` files but I kept getting the above error message when I used `MakeADFun`. I had to set my wd to where I locally cloned your github repo and `.../inst/executables/`.
