### ISSUE TITLE
Suggestion to avoid weird compilation bug

### ISSUE THREAD

**Issue by colemonnahan** [James-Thorson/spatial_factor_analysis#2]
I know this package is probably defunct now but people reading the paper and coming here (like me now) cannot reproduce the simulated example 

https://github.com/James-Thorson/spatial_factor_analysis/blob/master/examples/Simulated_example.R

because when installing the package SpatialFA it installs the .dll and .o files from an old version of TMB and so when you go to compile the model via [this line](https://github.com/James-Thorson/spatial_factor_analysis/blob/master/examples/Simulated_example.R#L29) it will throw weird compiler errors. 

The solution is simple: delete all the .dll and .o files from installation (put them in .gitignore).

**Comment by James-Thorson-NOAA** [comment]
Done. Thanks for tracking that down and providing an easy solution.
